DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS logs;

CREATE TABLE recipes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  directions TEXT[],
  ingredients JSONB NOT NULL
);

CREATE TABLE logs (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  date_of_event TEXT NOT NULL,
  notes TEXT NOT NULL,
  rating BIGINT NOT NULL,
  recipe_id BIGINT REFERENCES recipes(id)
);
